title: Riski Al Fatah
email: riski4alfattah@gmail.com
description: > 
    I am Riski Al Fatah, a student of Lhokseumawe State Polytechnic, my major is "Information & Computer Technology (ICT)" and my study program is Informatics Engineering.

url: "https://riskialfattah.github.io"

plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag